### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by ThisMe124** [Bumblebee-3/simpler-discord#1]
Heloo

**Comment by FightFarewellFearless** [comment]
nyasar lu?

**Comment by ThisMe124** [comment]
> nyasar lu?

Cara pakenya gimana bang

**Comment by FightFarewellFearless** [comment]
> Cara pakenya gimana bang

nti dibuat docs nya

**Comment by FightFarewellFearless** [comment]
> > nyasar lu?
> 
> Cara pakenya gimana bang

https://docs.pirles.tk
itu docs nya, belum jadi.

**Comment by Bumblebee-3** [comment]
mengapa membuat issue?

[I'm not Indonesian. Google translate go brr]

**Comment by ThisMe124** [comment]
> mengapa membuat issue?
> 
> [I'm not Indonesian. Google translate go brr]

Ku kira Ini akunnya si @FightFarewellFearless *alt account :v

**Comment by ThisMe124** [comment]
Just Gabutz

**Comment by ThisMe124** [comment]
> nyasar lu?

Btw Request $jsonRequest Function

**Comment by FightFarewellFearless** [comment]
> > nyasar lu?
> 
> Btw Request $jsonRequest Function

ok

**Comment by ThisMe124** [comment]
> > > nyasar lu?
> > 
> > 
> > Btw Request $jsonRequest Function
> 
> ok

Btw Request Again AutoUpdate package version options :)

**Comment by FightFarewellFearless** [comment]
> > > > nyasar lu?
> > > 
> > > 
> > > Btw Request $jsonRequest Function
> > 
> > 
> > ok
> 
> Btw Request Again AutoUpdate package version options :)

ok, bntr

**Comment by FightFarewellFearless** [comment]
udah, 
namanya "autoUpdateVersion"
taruh `autoUpdateVersion: true` di const bot nya

**Comment by ThisMe124** [comment]
> udah, namanya "autoUpdateVersion" taruh `autoUpdateVersion: true` di const bot nya

bjur Cepet Bet updatenya, btw ok

**Comment by ThisMe124** [comment]
> udah, namanya "autoUpdateVersion" taruh `autoUpdateVersion: true` di const bot nya

Add $supressErrors

**Comment by FightFarewellFearless** [comment]
> > udah, namanya "autoUpdateVersion" taruh `autoUpdateVersion: true` di const bot nya
> 
> Add $supressErrors

hmm, ok
