### ISSUE TITLE
I am go to support us

### ISSUE THREAD

**Issue by Emmannuel** [Bumblebee-3/simpler-discord#8]
Make server emoji count 
module.exports = {
name: "$guildEmojiCount",
usage: "[]",
description: "return emoji.count",
code: async (d) => {
return d.guild.emojis.cache.size
}
}

**Comment by FightFarewellFearless** [comment]
sure

**Comment by Emmannuel** [comment]
Also i can support in your package

**Comment by FightFarewellFearless** [comment]
> Also i can support in your package

with what u can support this package?

**Comment by duckytutorials** [comment]
Thank you for helping us i we thank you 

-- by duckey#3049 <3

**Comment by Bumblebee-3** [comment]
> Also i can support in your package



Sure. Thanks for your time and effort
